### ISSUE TITLE
Server crash: object is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#146]
On a user's instance, proxy keep crashing, with this error in logs:
```
TypeError: object is not a function
    at /usr/local/cozy/apps/proxy/build/server/models/user.js:63:23
    at /usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/lib/cozy_data_system.js:403:18
    at parseBody (/usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:26:12)
    at Request._callback (/usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:81:18)
    at self.callback (/usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:257:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1548:9)
    at Socket.emit (events.js:95:17)
```

**Comment by clochix** [comment]
@frankrousseau this seems to be the problem responsible for [server crashes reported by @nIQnutn](https://forum.cozy.io/t/error-504-gateway-time-out/950)

**Comment by frankrousseau** [comment]
@clochix DId you commit the build after your fix?
