### ISSUE TITLE
Proxy fails when opening Photos

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-proxy#150]
Cozy instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.0.2
Home: 2.0.4
Controller: 2.0.27

When I open Photos (application is stopped), it takes some time and open page with the following error:

![photos_error](https://cloud.githubusercontent.com/assets/1799460/8746913/51d5e9ac-2c8e-11e5-9f6b-7935e95f2a70.png)
The url is https://nicolas-6.cozycloud.cc/#apps/photos/

Proxy logs finish like this:

```
[Fri, 17 Jul 2015 12:07:26 GMT] - GET /apps/photos/ - - - - ms -  -
{ [Error: socket hang up] code: 'ECONNRESET' }
[2015-07-17 12:07:26:130] error - app:error | Error: socket hang up
[2015-07-17 12:07:26:131] error - app:error | Error: Error: socket hang up
    at ProxyServer.<anonymous> (/usr/local/cozy/apps/proxy/build/server/lib/proxy.js:39:11)
    at ProxyServer.emit (/usr/local/cozy/apps/proxy/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
    at ClientRequest.proxyError (/usr/local/cozy/apps/proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketCloseListener (http.js:1523:9)
    at Socket.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
```
and Photos logs:

```
[Fri, 17 Jul 2015 12:07:26 GMT] - GET / - - - - ms -  -
```

A stop/start of Photos do not solve anything (same error page and logs).

A restart of Cozy and a start of Photos gives another result:

![photos-error-2](https://cloud.githubusercontent.com/assets/1799460/8747028/62c0cce0-2c8f-11e5-8544-54fd5ca56d1d.png)

Photos logs are as follows:

```
[2015-07-17 12:19:53:397] error - Cozy DB | A request creation failed, abandon.
[2015-07-17 12:19:53:397] error - americano | cozydb failed to load.
[2015-07-17 12:20:55:601] error - Cozy DB | A request creation failed, abandon.
[2015-07-17 12:20:55:602] error - americano | cozydb failed to load.
nticated -- undefined] status: 401 }
[2015-07-17 12:19:53:893] info - americano | Routes loaded.
info - realtime-adapter | socket.io initialized
[2015-07-17 12:19:53:956] info - americano | Configuration for production loaded."
cozy-photos server is listening on port 9119...
[TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at Object.async.each (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:120:17)
    at /usr/local/cozy/apps/photos/build/server/controllers/album.js:40:18
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:32:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/photos/build/server/models/album.js:57:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
[Error: Callback was already called.]
Error: Callback was already called.
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:30:31
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/photos/build/server/models/album.js:57:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:32:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/photos/build/server/models/photo.js:50:16
[TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at Object.async.each (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:120:17)
    at /usr/local/cozy/apps/photos/build/server/controllers/album.js:40:18
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:32:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/api.js:69:16
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/model.js:240:16
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/model.js:198:20
[2015-07-17 12:20:55:527] info - americano | add plugin: cozydb
[2015-07-17 12:20:55:537] info - Cozy DB | album - all request creation...
{ [Error: expected: 200, got: 401 -- Application is not authenticated -- undefined] status: 401 }
{ [Error: expected: 200, got: 401 -- Application is not authenticated -- undefined] status: 401 }
[2015-07-17 12:20:56:22] info - americano | Routes loaded.
info - realtime-adapter | socket.io initialized
[2015-07-17 12:20:56:47] info - americano | Configuration for production loaded."
cozy-photos server is listening on port 9119...
```
Ultimate option, uninstall and install of Photos, which gives the same error page and logs.

Ultimate-Ultimate option restart Cozy... and Yes it's alive !

I hope these informations will help you identtify what is hapenning.

**Comment by aenario** [comment]
Whoah, thanks @nicodel for the extensive report !

@poupotte , this appears to be linked to the authorization problem you are investigating. May be these logs can help you.

**Comment by clochix** [comment]
I think there may be two problems here : 
  -the first reported by @nicodel : seems like Photo took too long to answer and the proxy canceled the request;
 - after the server restart, the photo application crashed, probably because we don't handle the error case here https://github.com/cozy/cozy-photos/blob/master/server/controllers/album.coffee#L24

@nicodel do you still have problems opening the photo application ?

**Comment by nicodel** [comment]
@clochix , No I could not reproduce. I try several times, and even if Photos is slow to start/open, it is displayed correctly.
I think this bug could be closed.
I'll let you decide/

**Comment by clochix** [comment]
Thanks @nicodel for your feedback. I opened cozy/cozy-photos#149 for the crash in photo server.
I close this one, @aenario, @poupotte, feel free to re-open it needed.
