### ISSUE TITLE
Server crash: next is not defined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#223]
```
next is not defined
ReferenceError: next is not defined
    at /usr/local/cozy/apps/proxy/build/server/controllers/index.js:25:14
    at /usr/local/cozy/apps/proxy/build/server/lib/router.js:47:18
    at parseBody (/usr/local/cozy/apps/proxy/node_modules/request-json/main.js:35:12)
    at Request._callback (/usr/local/cozy/apps/proxy/node_modules/request-json/main.js:77:18)
    at Request.self.callback (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:978:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:929:12)
    at IncomingMessage.emit (events.js:117:20)
null
```

**Comment by poupotte** [comment]
Thanks @clochix :+1:
