### ISSUE TITLE
Server error: TypeError: object is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#227]
```
error - app:error | TypeError: object is not a function
    at View.config.common.engine.js [as engine] (/usr/local/cozy/apps/proxy/build/server/config.js:48:44)
    at View.render (/usr/local/cozy/apps/proxy/node_modules/americano/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/usr/local/cozy/apps/proxy/node_modules/americano/node_modules/express/lib/application.js:521:10)
    at ServerResponse.res.render (/usr/local/cozy/apps/proxy/node_modules/americano/node_modules/express/lib/response.js:818:7)
    at /usr/local/cozy/apps/proxy/build/server/controllers/authentication.js:128:18
    at /usr/local/cozy/apps/proxy/build/server/controllers/authentication.js:39:12
    at /usr/local/cozy/apps/proxy/build/server/models/user.js:91:12
    at /usr/local/cozy/apps/proxy/build/server/models/user.js:72:14
    at /usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/lib/cozy_data_system.js:413:18
    at parseBody (/usr/local/cozy/apps/proxy/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:26:12)

```

**Comment by nono** [comment]
It was probably a build error where locales were missing. I think we can close this issue.

**Comment by frankrousseau** [comment]
@clochix Repoen it if someone complains again.
