### ISSUE TITLE
[2FA] First OTP login failed

### ISSUE THREAD

**Issue by Toobian** [cozy/cozy-proxy#291]
Hi,

When i try to login with otp, the first submission failed. But when i retry (just click on submit button, no change in inputs), it's working.

Below, proxy's logs about login process :
```
[Thu, 07 Jul 2016 08:29:23 GMT] - GET /routes/reset - 200 - 204.903 ms -  16
[2016-07-07 08:29:23:978] error - app:error | error otp invalid code
[2016-07-07 08:29:23:979] error - app:error | error otp invalid code
[2016-07-07 08:29:23:982] error - app:error | Error: error otp invalid code
    at makeError (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/middlewares/authentication.js:29:9)
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/middlewares/authentication.js:84:21
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/models/user.js:74:14
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/lib/model.js:213:18
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/lib/cozymodel.js:294:18
    at parseBody (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
[2016-07-07 08:29:23:985] error - app:error | Error: error otp invalid code
    at makeError (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/middlewares/authentication.js:29:9)
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/middlewares/authentication.js:84:21
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/build/server/models/user.js:74:14
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/lib/model.js:213:18
    at /usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/lib/cozymodel.js:294:18
    at parseBody (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/cozy-proxy/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
[Thu, 07 Jul 2016 08:29:23 GMT] - POST /login - 401 - 7420.390 ms -  63
[Thu, 07 Jul 2016 08:29:29 GMT] - POST /login - 200 - 274.811 ms -  16
```

**Comment by babolivier** [comment]
Hi @Toobian, 
This is à known issue, as reportée in #280. I'll try to find some time to fix this ASAP.
